/**
 * wc_cobra    lines    filename1 filename2 ...
 * wc_cobra    bytes    filename1 filename2 ...
 * wc_cobra    chars    filename1 filename2 ...
 * wc_cobra    longest  filename1 filename2 ...
 * wc_cobra    words    filename1 filename2 ...
 */

package main

import "wc_cobra/cmd"

func main() {
   cmd.Execute()
}
