
// https://godbolt.org/z/1boeTMMvf 
MxStack<int> mxs{};
// …
// more code
// …
if( ! mxs.isEmpty()) {            // (ERR) not safe
    const auto value = mxs.top(); // (ERR) not safe
    mxs.pop();                    // (ERR) not safe
    // …
    // more code
    // …
}