DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    userId     INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username   VARCHAR(30) NOT NULL,
    password   VARCHAR(30) NOT NULL,
    last_login INTEGER,
    admin      INTEGER,
    active     INTEGER
);

INSERT INTO users (username, password, last_login, admin, active)
VALUES ('admin', 'admin', 1620922454, 1, 1);
