[package]
name = "action_kv_final"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.2"
crc = "1.7"

[lib]
name = "libactionkv"
path = "src/lib.rs"

[[bin]]
name = "action_kv_final"
path = "src/akv_mem.rs"